#pragma once

#include <cassert>              // for assert
#include <cstdint>              // for uint32_t
#include <iostream>             // for ostream
#include <kaad/exceptions.hpp>  // for argument_error
#include <kaad/graph/graph.hpp> // for computation_graph

namespace kaad {
class Graph;

/**
 * @brief Immutable handle class for a INode.
 */
class Node {
    uint32_t idx_;  ///< Index of the node in the Graph.
    Graph *origin_; ///< Pointer to the correct Graph.

    /**
     * @brief private constructor
     * @param idx Index of the node in the Graph.
     * @param origin Pointer to the Graph.
     */
    constexpr explicit Node(uint32_t idx, Graph *origin) noexcept
        : idx_(idx), origin_(origin) {}

    friend class Graph;

  public:
    /**
     * @brief Get the index.
     * @return Copy of the idx_ member.
     */
    [[nodiscard]] constexpr uint32_t idx() const noexcept { return this->idx_; }

    /**
     * @brief Get the origin of the Node.
     * @return Pointer to the Graph which contains the node.
     */
    [[nodiscard]] constexpr const Graph *origin() const noexcept {
        return this->origin_;
    }

    /**
     * @brief Returns an immutable pointer to the node.
     * @return Const pointer to the node.
     */
    [[nodiscard]] const INode *node() const {
        if (this->idx() >= this->origin_->nodes.size()) {
            throw argument_error("idx_ of this handle is invalid");
        }

        return this->origin_->nodes[this->idx()].get();
    }

    /**
     * @brief Get the element array of the value tensor.
     * @warning Only usable on node generated by @ref add_input_node.
     * @return A std::range of the element array.
     */
    std::span<Scalar> value_elements() {
        assert(this->node()->isInput());

        Tensor &value = this->origin_->get_node(*this)->value();
        return {value.data(), value.size()};
    }

    /**
     * @brief Get immutable value tensor of the node.
     * @return Const reference to the value tensor of the node.
     */
    [[nodiscard]] const Tensor &value() const { return this->node()->value(); }

    /**
     * @brief Get immutable gradient tensor of the node.
     * @return Const reference to the gradient tensor of the node.
     */
    [[nodiscard]] const Tensor &gradient() const {
        return this->node()->gradient();
    }

    friend constexpr auto operator<=>(Node, Node) = default;
    friend std::ostream &operator<<(std::ostream &stream, Node node);
};

} // namespace kaad
